### ISSUE TITLE
Will Not Build

### ISSUE THREAD

**Issue by tcables** [chequer-io/JDBC.NET#28]
Hello,

I've tried to clone your latest code and build as debug. I receive the following error:

"Could not copy the file "Could not copy the file "C:\source\JDBC.NET\JDBC.NET.Bridge\target\JDBC.NET.Bridge-1.0-SNAPSHOT-jar-with-dependencies.jar" because it was not found."

I am using Visual Studio 2022 Community Edition. Fresh clone, no changes, immediate attempt to build.

Edit: If I build as Release, I do not receive the error, but I cannot debug.

**Comment by Bas-Boven** [comment]
Did you also build the included java application?

**Comment by tcables** [comment]
Good call, I did not notice that there was a Java app that needed to be built.
